name: wow

on:
  push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          env | sort
          echo OLD DATE: $(cat wow.date)
          date | tee wow.date
          git config --local user.email "bryan.schofield@libertyits.com"
          git config --local user.name "Bryan Schofield"
          git add .
          git commit -m "wow"
          BRANCH=master
          REMOTE_REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${REMOTE_REPO}" HEAD:${BRANCH} --follow-tags --tags

