name: wow

on:
  push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          env | sort
          set -x
          mvn deploy -s settings.xml
          docker login docker.pkg.github.com --username ${GITHUB_ACTOR} --password ${GITHUB_TOKEN}
          echo OLD DATE: $(cat wow.date)
          date | tee wow.date
          TAG=docker.pkg.github.com/bschofield-va/action-test/wow:latest
          docker build -t $TAG .
          docker push $TAG
          git config --local user.email "bryan.schofield@libertyits.com"
          git config --local user.name "Bryan Schofield"
          git add .
          git commit -m "wow"
          BRANCH=master
          REMOTE_REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${REMOTE_REPO}" HEAD:${BRANCH} --follow-tags --tags
          

